package tn.esprit.thewalkingdev.gui.controller;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.event.ActionEvent;

public class addEventController {
	@FXML
	private Button button;

	// Event Listener on Button[#button].onAction
	@FXML
	public void button(ActionEvent event) {
		// TODO Autogenerated
	}
}
