package tn.esprit.thewalkingdev.gui.controller;

import java.net.URL;
import java.util.ResourceBundle;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;
import javafx.event.ActionEvent;
import javafx.scene.control.TableColumn;

public class AddOwnerController implements Initializable, ControlledScreen {
	
	ScreensController ctr;
	
	@FXML
	private TableColumn nameOwner;
	@FXML
	private Button addOwner;

	// Event Listener on Button[#addOwner].onAction
	@FXML
	public void addOwner(ActionEvent event) {
		// TODO Autogenerated
	}

	@Override
	public void setScreenParent(ScreensController screenPage) {
		ctr = screenPage;
		
	}

	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		// TODO Auto-generated method stub
		
	}
}
