package tn.esprit.thewalkingdev.gui.controller;

import java.io.IOException;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.stage.Stage;
import javafx.event.ActionEvent;

public class DisplayEventController {
	@FXML
	private Button displayAddEvent;
	@FXML
	private Button displayUpdateEvent;
	@FXML
	private Button deleteEvent;

	// Event Listener on Button[#displayAddEvent].onAction
	@FXML
	public void displayAddEvent(ActionEvent event) {
		try {
			FXMLLoader loader = new FXMLLoader();
	        loader.setLocation(getClass().getResource("/tn/esprit/thewalkingdev/gui/view/AddEvent.fxml"));
	        
				loader.load();
				Parent P = loader.getRoot();
		        Stage stage = new Stage();
		        stage.setScene(new Scene(P));
		        stage.show();
			} catch (IOException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
	}
	// Event Listener on Button[#displayUpdateEvent].onAction
	@FXML
	public void displayUpdateEvent(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#deleteEvent].onAction
	@FXML
	public void deleteEvent(ActionEvent event) {
		// TODO Autogenerated
	}
}
