package tn.esprit.thewalkingdev.gui.controller;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.event.ActionEvent;

import javafx.scene.control.TextArea;

public class SendMailController {
	@FXML
	private Button BtSendMail;
	@FXML
	private TextArea TFMail;

	// Event Listener on Button[#BtSendMail].onAction
	@FXML
	public void SendMail(ActionEvent event) {
		// TODO Autogenerated
	}
}
